version: 2.1

references:
  environment_functions: &environment_functions
    working_directory: ~/repo
    docker:
        - image: cimg/node:12.22.1

  restore_cache: &restore_cache
    restore_cache:
      keys:
          - v1-dependencies-{{ checksum "~/repo/yarn.lock" }}
          - v1-dependencies-

  save_cache: &save_cache
    save_cache:
      paths:
        - ~/repo/node_modules
      key: v1-dependencies-{{ checksum "~/repo/yarn.lock" }}

jobs:
    build_and_test_functions:
        <<: *environment_functions

        steps:
            - checkout
            - *restore_cache
            - run:
                name: Install dependencies
                command: yarn install && yarn bootstrap
            - *save_cache
            - run:
                name: Install fstore
                command: npm install --prefix=$HOME/.local --global @fstore/cli@0.4.1-canary.3
            - run:
                name: Login fstore
                command: fstore login --token $FSTORE_TOKEN
            - run:
                name: ESLint
                command: yarn lint
            - run:
                name: Fstore lint
                command: fstore lint
            - run:
                name: Test
                command: yarn test
                environment:
                  JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
            - store_test_results:
                path: ~/repo/reports/junit/

    push_fstore:
        <<: *environment_functions

        steps:
            - checkout
            - *restore_cache
            - run:
                name: Install dependencies
                command: yarn install && yarn bootstrap
            - run:
                name: Install fstore
                command: npm install --prefix=$HOME/.local --global @fstore/cli@0.4.1-canary.3
            - run:
                name: Login fstore
                command: fstore login --token $FSTORE_TOKEN
            - run:
                name: Push workspace
                command: fstore push

workflows:
    version: 2
    workflow:
        jobs:
            - build_and_test_functions
            - push_fstore:
                context: functions.store-learning.dev
                requires:
                    - build_and_test_functions
                filters:
                    branches:
                        only: master

