version: 2.1

orbs:
  node: circleci/node@4.1.1

jobs:
  test:
    docker:
      - image: cimg/node:16.1.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn lint
      - run:
          name: Login fstore
          command: yarn fstore:login --token $FSTORE_TOKEN
      - run:
          name: Fstore lint
          command: yarn fstore:lint
      - run:
          name: Run Jest Test
          command: yarn test --runInBand --ci --coverage --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/

  push_fstore:
    docker:
      - image: cimg/node:16.1.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn bootstrap
      - run:
          name: Login fstore
          command: yarn fstore:login login --token $FSTORE_TOKEN
      - run:
          name: Push workspace
          command: yarn fstore:push

workflows:
  workflow:
    jobs:
      - test
      - push_fstore:
          requires:
            - test
          filters:
            branches:
              only: master
